# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

inhibit_all_warnings!

  # Pods for Flix
	pod 'AFNetworking'
	pod 'MBProgressHUD'
    pod 'CircularSpinner'
    pod 'FloatRatingView', '~> 2.0.0'
end
